### ISSUE TITLE
Infografía-Irvin Salathiel Barrera Valencia

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-salathiel1999#1]
[Infografía-Irvin Salathiel Barrera Valencia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-salathiel1999/files/14235828/Infografia-Irvin.Salathiel.Barrera.Valencia.pdf)

**Comment by NoeliaGlez** [comment]
19%

**Comment by josealfredo79** [comment]
@NoeliaGlez Revisar bien la calificacion por favor...
